### ISSUE TITLE
Genre list is empty

### ISSUE THREAD

**Issue by trolley** [UweTrottmann/thetvdb-java#12]
I'm using your API to request the series info for Futurama but am finding the genre list is empty. On [The TVDB page](https://www.thetvdb.com/series/futurama) it has 3 genres: Animation, Comedy, Science-Fiction

**Comment by UweTrottmann** [comment]
Nothing wrong on my end (using `TheTvdbSeriesTest#test_series`):
![image](https://user-images.githubusercontent.com/888674/39619122-e6ad76f8-4f86-11e8-8162-217674f66029.png)
![image](https://user-images.githubusercontent.com/888674/39619105-d8b04332-4f86-11e8-8654-a41ccc5fed0d.png)
Probably a short hiccup due to the launch of the new site?

**Comment by trolley** [comment]
Strange, it still fails for me:

<img width="608" alt="genres" src="https://user-images.githubusercontent.com/1136971/39627723-cddd778e-4f74-11e8-9ba4-4252489ed519.png">

Same with rating as I'd reported in the other issue:

<img width="611" alt="rating" src="https://user-images.githubusercontent.com/1136971/39627738-dbf1de1e-4f74-11e8-8514-0a682506952d.png">

I'll take a look at your test series code to see if I'm doing something wrong when I to the series search.

**Comment by trolley** [comment]
Whoops...I was using the `Series` object returned in `SeriesResultsResponse`, not from a `SeriesResponse`. I see now that the second has all the data. Sorry about that.
